services:
  postgres:
    image: postgres:18
    container_name: eteg-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-eteg}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-eteg}
      POSTGRES_DB: ${DB_DATABASE:-eteg}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
