/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Clients: () => import('#controllers/clients_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  Home: () => import('#controllers/home_controller'),
  Session: () => import('#controllers/session_controller'),
}
